const { contextBridge, ipcRenderer } = require('electron');
const listen = (channel, callback) => {
  const listener = (_event, value) => callback(value);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
};
contextBridge.exposeInMainWorld('convoy', {
  scanTranscripts: (projectID, agent, profileID) => ipcRenderer.invoke('transcripts:scan', projectID, agent, profileID),
  importTranscript: id => ipcRenderer.invoke('transcripts:import', id),
  toggleQueue: id => ipcRenderer.invoke('queue:toggle', id),
  usage: id => ipcRenderer.invoke('usage:read', id),
  onStatus: callback => listen('agent:status', callback),
  platform: process.platform,
  files: id => ipcRenderer.invoke('files:snapshot', id),
  fileRead: (id, request) => ipcRenderer.invoke('files:read', id, request),
  fileAction: (id, action, value) => ipcRenderer.invoke('files:mutate', id, action, value),
  discover: () => ipcRenderer.invoke('project:discover'),
  editProject: (id, patch) => ipcRenderer.invoke('project:edit', id, patch),
  reconnectProject: id => ipcRenderer.invoke('project:reconnect', id),
  removeProject: id => ipcRenderer.invoke('project:remove', id),
  removeProfile: id => ipcRenderer.invoke('profile:remove', id),
  recover: id => ipcRenderer.invoke('session:recover', id),
  read: () => ipcRenderer.invoke('workspace:read'),
  openFolder: () => ipcRenderer.invoke('project:open'),
  createSession: details => ipcRenderer.invoke('session:create', details),
  editSession: (id, patch) => ipcRenderer.invoke('session:edit', id, patch),
  saveSettings: settings => ipcRenderer.invoke('settings:save', settings),
  saveSpec: input => ipcRenderer.invoke('spec:save', input),
  approveSpec: (id, revision) => ipcRenderer.invoke('spec:approve', id, revision),
  exportSpec: id => ipcRenderer.invoke('spec:export', id),
  saveTask: input => ipcRenderer.invoke('task:save', input),
  taskStatus: (id, status) => ipcRenderer.invoke('task:status', id, status),
  prepareTask: (id, profileID) => ipcRenderer.invoke('task:prepare', id, profileID),
  addProfile: (label, agent) => ipcRenderer.invoke('profile:add', label, agent),
  saveCommand: command => ipcRenderer.invoke('command:save', command),
  deleteCommand: id => ipcRenderer.invoke('command:delete', id),
  sendCommand: (id, commandID) => ipcRenderer.invoke('command:send', id, commandID),
  history: id => ipcRenderer.invoke('history:read', id),
  reviewBrief: id => ipcRenderer.invoke('review:brief', id),
  feedback: (id, text) => ipcRenderer.invoke('review:feedback', id, text),
  paste: (id, text) => ipcRenderer.invoke('terminal:paste', id, text),
  gitStatus: id => ipcRenderer.invoke('git:status', id),
  createWorktree: (id, branch) => ipcRenderer.invoke('worktree:create', id, branch),
  removeWorktree: id => ipcRenderer.invoke('worktree:remove', id),
  start: id => ipcRenderer.invoke('terminal:start', id),
  stop: id => ipcRenderer.invoke('terminal:stop', id),
  write: (id, data) => ipcRenderer.invoke('terminal:write', id, data),
  resize: (id, cols, rows) => ipcRenderer.invoke('terminal:resize', id, cols, rows),
  onData: callback => listen('terminal:data', callback),
  onExit: callback => listen('terminal:exit', callback),
  onChange: callback => listen('workspace:changed', callback),
  onError: callback => listen('app:error', callback),
  onFocus: callback => listen('session:focus', callback)
});
